baseURL = "https://devflow.github.io/"
title = "devflow"

copyright = ""
theme = "df"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

enableRobotsTXT = true
enableEmoji = true

preserveTaxonomyNames = true

disqusShortname = "bdevflow"


[permalinks]
  posts = "/posts/:filename/"
  projects = "/projects/:filename/"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/_devflow"

[[params.social]]
  name = "email"
  url  = "mailto:admin@devflow.kr"

[[params.social]]
  name = "github"
  url  = "https://github.com/devflow"